flight_log:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      location: US
      dataset: data_warehouse
      priority: interactive
      job_execution_timeout_seconds: 600
      job_retries: 1
      threads: 1
      keyfile_json:
        type: service_account
        project_id: "{{ env_var('GCP_PROJECT_ID') }}"
        private_key_id: "{{ env_var('GCP_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('GCP_PRIVATE_KEY') }}"
        client_email: "{{ env_var('GCP_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('GCP_CLIENT_ID') }}"
        auth_uri: "{{ env_var('GCP_AUTH_URI') }}"
        token_uri: "{{ env_var('GCP_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('GCP_AUTH_PROVIDER') }}"
        client_x509_cert_url: "{{ env_var('GCP_CLIENT_CERT_URL') }}"
