name: publish dbt docs

on:
  push:
    branches:
      - main

jobs:
  publish_dbt_docs:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install dbt-bigquery
      - run: echo "${{ secrets.GCP_CREDENTIALS }}" > secrets/gcloud.json 
      - run: dbt docs generate
        working-directory: dbt/flight_log/
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dbt/flight_log/target/
      - run: rm secrets/gcloud.json
