name: run dbt

on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  run_dbt:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install dbt-bigquery
      - run: echo '${{ secrets.GCP_CREDENTIALS }}' > secrets/gcloud.json
      - run: dbt run
        working-directory: dbt/flight_log/
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      - run: rm secrets/gcloud.json
